language: python

cache: pip

python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"

install:
    - python setup.py install

script:
    - nosetests

after_success:
  - bash <(curl -s https://codecov.io/bash)
